name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - .github/workflows/*

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      python_ver: "3.11"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_ver }}

      - name: Get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: plugin.json
          prop_path: Version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Create plugin zip
        run: |
          zip -r "Stremio-Search-${{ steps.version.outputs.prop }}.zip" \
            plugin.json \
            main.py \
            SettingsTemplate.yaml \
            plugin \
            assets \
            -x "*.pyc" \
            -x "*/__pycache__/*"

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: "Stremio-Search-${{ steps.version.outputs.prop }}.zip"
          tag_name: "v${{ steps.version.outputs.prop }}"
